- name: Installer Nginx
  apt:
    name: nginx
    state: present

- name: Démarrer le service Nginx et l'activer au démarrage
  service:
    name: nginx
    state: started
    enabled: yes

- name: Supprimer la configuration par défaut de Nginx
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Redémarrer Nginx

- name: Configurer le Vhost kk-bs
  template:
    src: vhost.j2
    dest: /etc/nginx/sites-available/kapsule.conf
  notify: Redémarrer Nginx

- name: Activer le site (lien symbolique)
  ansible.builtin.file:
    src: /etc/nginx/sites-available/kapsule.conf
    dest: /etc/nginx/sites-enabled/kapsule.conf
    state: link
  notify: Redémarrer Nginx

- name: Déployer la page d'accueil PHP (index.php)
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
  notify: Redémarrer Nginx

- name: Supprimer le index.html par défaut
  ansible.builtin.file:
    path: /var/www/html/index.nginx-debian.html
    state: absent