$ANSIBLE_VAULT;1.1;AES256
30633261313739333936313863306661633238613362343233323966623632303337396433383662
3935383135613237656562333437323361643564376663630a383531323531623433313033373431
39393133343262616136633735396262646564363166313563313561326363616131353135643830
3563643161323861610a623864383339333436303134313333633838373939386562343939633435
36313832303062336338666635396163316261633332663734383836336134623931643637383163
31396461653135376535656134363264616138616636346461653630393537663034633161376561
31653134666639393666366534363862646638373865363232363737353935363662636430393631
62616562343135303132623037393034393835353365383464633663316431346132393731303561
38373133386233316434633561336465343138646262646439336130313766303261643037373635
62663765316566316262353330363930653166366666346639363066343238643436316530336539
38303962343530616433653930623433646466376430663462343739313431313634663030396163
31343433323037373837
