$ANSIBLE_VAULT;1.1;AES256
30636331383638363064616133643235313234623134613434346632663765623236326436333764
3636626132626136316261616136356537333034646333640a343339333836313764356361643331
36346261623431366537646132333561323030333461343035666332666263393239666566366133
3337373961346531380a363639613732316534653132653034636237656664363366656164613064
62303234363934356236666666663661663739306132356538313132363936303432
