$ANSIBLE_VAULT;1.1;AES256
36646264313936386537373361656164613262313065633837663934616135346335373236343430
3663613833616235313831383237623538333465343366390a336635653032353065643735623538
32633936393263383232343365633739393731353239366333653930313163613439666535366366
6463353237346135640a663931663232653532346235646630366661643433613534633931343730
32326632303965313565323233376237646438383334346434626136396131646531653930353736
31306463356332623533616634383631613233643766396262656464626331373663653361613230
62353064343238626332353365636263373166313661316335393664366433663130373462326439
66383439643862333261306536666563373836396262383264376138616566383534643661643862
34646532326166386235646366643062373236353838303536336661653962616165363132646435
31616337346635356339396362336233613665626535336235613034393564303937343133333933
36306666383263653339366662303631613132363964623735633638663132613337373037663231
61653636666134613238
